/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.1.3135.0) */

#include "service_if.h"
#include <stdint.h>
#include "app_trace.h" 
#include "ble_peggy_peripheral.h" 

static ble_peggy_peripheral_t    m_peggy_peripheral;


/**@brief Function for handling the pEggy peripheral events.
 *
 * @details This function will be called for all pEggy peripheral events which are passed to
 *          the application.
 *
 * @param[in]   p_peggy_peripheral   pEggy peripheral structure.
 * @param[in]   p_evt   Event received from the pEggy peripheral.
 */
static void on_peggy_peripheral_evt(ble_peggy_peripheral_t * p_peggy_peripheral, ble_peggy_peripheral_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_PEGGY_PERIPHERAL_COIN_EVENT_NOTIFICATION_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: PEGGY_PERIPHERAL_COIN_EVENT_NOTIFICATION evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_PEGGY_PERIPHERAL_COIN_EVENT_NOTIFICATION_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: PEGGY_PERIPHERAL_COIN_EVENT_NOTIFICATION evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_PEGGY_PERIPHERAL_COIN_EVENT_NOTIFICATION_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: PEGGY_PERIPHERAL_COIN_EVENT_NOTIFICATION evt CCCD_WRITE. \r\n");
            break; 
        case BLE_PEGGY_PERIPHERAL_DATE_TIME_EVT_WRITE:
            app_trace_log("[Bluetooth_IF]: PEGGY_PERIPHERAL_DATE_TIME evt WRITE. \r\n");
            break; 
        case BLE_PEGGY_PERIPHERAL_PENDING_TRANSACTIONS_INDICATOR_EVT_NOTIFICATION_ENABLED:
            app_trace_log("[Bluetooth_IF]: PEGGY_PERIPHERAL_PENDING_TRANSACTIONS_INDICATOR evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_PEGGY_PERIPHERAL_PENDING_TRANSACTIONS_INDICATOR_EVT_NOTIFICATION_DISABLED:
            app_trace_log("[Bluetooth_IF]: PEGGY_PERIPHERAL_PENDING_TRANSACTIONS_INDICATOR evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_PEGGY_PERIPHERAL_PENDING_TRANSACTIONS_INDICATOR_EVT_CCCD_WRITE:
            app_trace_log("[Bluetooth_IF]: PEGGY_PERIPHERAL_PENDING_TRANSACTIONS_INDICATOR evt CCCD_WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t bluetooth_init(void)
{
    uint32_t    err_code; 
    ble_peggy_peripheral_init_t    peggy_peripheral_init; 
    

    // Initialize pEggy peripheral.
    memset(&peggy_peripheral_init, 0, sizeof(peggy_peripheral_init));

    peggy_peripheral_init.evt_handler = on_peggy_peripheral_evt; 
    memset(&peggy_peripheral_init.ble_peggy_peripheral_coin_event_notification_initial_value.new_coin,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_coin_event_notification_initial_value.new_coin));
    peggy_peripheral_init.is_date_time_read_supported = true;
    peggy_peripheral_init.is_date_time_write_supported = true;
    memset(&peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.year,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.year));
    peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.month.month = MONTH_MONTH_IS_NOT_KNOWN; 
    memset(&peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.day,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.day));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.hours,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.hours));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.minutes,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.minutes));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.seconds,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_date_time_initial_value.seconds));
    peggy_peripheral_init.is_pending_transactions_read_supported = true;
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.year,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.year));
    peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.month.month = MONTH_MONTH_IS_NOT_KNOWN; 
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.day,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.day));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.hours,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.hours));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.minutes,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.minutes));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.fives,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.fives));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.twos,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.twos));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.ones,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.ones));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.fiftys,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.fiftys));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.twenties,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.twenties));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.tens,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_initial_value.tens));
    memset(&peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_indicator_initial_value.pending_transactions,
           0x00,
           sizeof(peggy_peripheral_init.ble_peggy_peripheral_pending_transactions_indicator_initial_value.pending_transactions));

    err_code = ble_peggy_peripheral_init(&m_peggy_peripheral, &peggy_peripheral_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_peggy_peripheral_on_ble_evt(&m_peggy_peripheral, p_ble_evt); 
}

void test_function(uint8_t notification_code)
{
	if(m_peggy_peripheral.conn_handle != BLE_CONN_HANDLE_INVALID)
	{
		//BLE_PEGGY_PERIPHERAL_COIN_EVENT_NOTIFICATION_EVT_NOTIFICATION_ENABLED;
		ble_peggy_peripheral_coin_event_notification_t notify;
		notify.new_coin = notification_code;
		
		uint32_t    err_code; 
		err_code = ble_peggy_peripheral_coin_event_notification_send(&m_peggy_peripheral, &notify);
	}
}
